### ISSUE TITLE
안녕하세요, 디코봇이랑 연동해서 사용을 하려고 하는데 

### ISSUE THREAD

**Issue by rc0n9027** [MinecraftTorch/TorchDonation#5]
**서버 환경**
 - OS: WINDOWS10
 - Java 버전: JDK14

```
2022-08-29 22:55:54 [ ERROR] One of the EventListeners had an uncaught exception
java.lang.NullPointerException: null
	at command.Redeem.onMessageReceived(Redeem.java:35)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:133)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

```
private static void generateQueue() throws Session.LoginFailureException {
        Session session = new Session();

        try {
            session.login();
            System.out.println("1");
        } catch (Session.LoginFailureException | JSONException e) {
            throw new Session.LoginFailureException();
        }

        taskQueue = new TaskQueue(session); <-- 요게 안먹히는거 같습니다.
        System.out.println("2");
    }
```

session.login() 이쪽에 sout 1이 잘 출력이 잘되는데 
taskQueue = new TaskQueue(session); 아래에 sout 2는 출력이 안되네요 ㅠㅠ
크롬이 열리고 로그인까지 모두 정상적으로 되는데, 핀 번호를 입력하게 되면 ConfigValues.taskQueue.enqueue(userDonation); 이쪽에서 taskQueue가 null이라고 위 에러가 발생합니다.

**Comment by isu-kim** [comment]
우선 플러그인에 대한 관심 감사합니다.

## Stacktrace 의 경우...
제공해주신 stacktrace 또한 이 플러그인에서 생긴 문제인지, 다른 곳에서 생긴 문제인지 모르겠습니다. `com.neovisionaries`, `net.dv8tion` 중 어느쪽도 저희 플러그인이랑 관련된 문제는 아니기에, 제공해주시느 stacktrace 의 경우 이 플러그인의 어디가 잘못 되었다고 말씀을 못드리겠네요.
## 다른 가능성
개발 환경 및 마인크래프트 서버 테스트시 1.19 과 같은 고 버전으로 테스트하였고, JDK18 로 플러그인을 제작했기에 JDK14 에서는 동작 확인이 되지 않았습니다. 

Issue 를 다시 *양식에 맞추어서* 열어주시면 감사하겠습니다.
